# Generated by Django 4.0.6 on 2022-07-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store_addr',
            fields=[
                ('store_no', models.AutoField(primary_key=True, serialize=False)),
                ('addr_depth_1', models.CharField(max_length=5)),
                ('addr_depth_2', models.CharField(max_length=5)),
                ('addr_depth_3', models.CharField(max_length=10)),
                ('addr_depth_4', models.CharField(max_length=20)),
                ('reg_dtime', models.DateTimeField(blank=True, null=True)),
                ('mod_dtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'store_addr',
            },
        ),
        migrations.CreateModel(
            name='store_info',
            fields=[
                ('store_no', models.AutoField(primary_key=True, serialize=False)),
                ('store_name_kor', models.CharField(max_length=100)),
                ('store_name_eng', models.CharField(max_length=100)),
                ('store_tel', models.CharField(max_length=15)),
                ('opening_time', models.TextField(blank=True, null=True)),
                ('store_sns', models.TextField(blank=True, null=True)),
                ('reg_dtime', models.DateTimeField(blank=True, null=True)),
                ('mod_dtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'store_info',
            },
        ),
        migrations.CreateModel(
            name='store_menu',
            fields=[
                ('store_no', models.AutoField(primary_key=True, serialize=False)),
                ('memu_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'store_menu',
            },
        ),
    ]
