# Generated by Django 4.0.6 on 2022-08-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noffeine_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeAddr',
            fields=[
                ('cafe_no', models.AutoField(primary_key=True, serialize=False)),
                ('addr_depth_1', models.CharField(max_length=5)),
                ('addr_depth_2', models.CharField(max_length=5)),
                ('addr_depth_3', models.CharField(max_length=10)),
                ('addr_depth_4', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=11)),
                ('reg_dtime', models.DateTimeField(auto_now_add=True)),
                ('mod_dtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cafe_addr',
            },
        ),
        migrations.CreateModel(
            name='CafeInfo',
            fields=[
                ('cafe_no', models.AutoField(primary_key=True, serialize=False)),
                ('cafe_name_kor', models.CharField(max_length=100)),
                ('cafe_name_eng', models.CharField(max_length=100)),
                ('cafe_tel', models.CharField(max_length=15)),
                ('opening_time', models.JSONField(default='{}')),
                ('is_operating', models.BooleanField(default=True)),
                ('cafe_sns', models.TextField(blank=True, null=True)),
                ('reg_dtime', models.DateTimeField(auto_now_add=True)),
                ('mod_dtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cafe_info',
            },
        ),
        migrations.CreateModel(
            name='CafeMenu',
            fields=[
                ('cafe_no', models.AutoField(primary_key=True, serialize=False)),
                ('memu_url', models.TextField(blank=True, null=True)),
                ('reg_dtime', models.DateTimeField(auto_now_add=True)),
                ('mod_dtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cafe_menu',
            },
        ),
        migrations.DeleteModel(
            name='store_addr',
        ),
        migrations.DeleteModel(
            name='store_info',
        ),
        migrations.DeleteModel(
            name='store_menu',
        ),
    ]
