# Generated by Django 4.0.6 on 2022-08-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noffeine_app', '0002_cafeaddr_cafeinfo_cafemenu_delete_store_addr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeinfo',
            name='opening_time',
            field=models.JSONField(default={}),
        ),
    ]
