# Generated by Django 4.0.6 on 2022-08-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noffeine_app', '0003_alter_cafeinfo_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeinfo',
            name='opening_time',
            field=models.JSONField(default=dict),
        ),
    ]
