# Generated by Django 4.0.6 on 2022-08-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noffeine_app', '0005_alter_cafeinfo_cafe_sns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeinfo',
            name='cafe_name_eng',
        ),
        migrations.RemoveField(
            model_name='cafeinfo',
            name='cafe_name_kor',
        ),
        migrations.AddField(
            model_name='cafeinfo',
            name='cafe_name',
            field=models.JSONField(default=dict),
        ),
    ]
