# Generated by Django 4.0.6 on 2022-08-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noffeine_app', '0006_remove_cafeinfo_cafe_name_eng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafemenu',
            old_name='memu_url',
            new_name='menu_url',
        ),
    ]
